# Generated by Django 3.1.3 on 2020-11-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Watch', 'Watch'), ('Bag', 'Bag'), ('Accessories', 'Accessories')], default=None, max_length=20),
        ),
    ]
